app_front_office:
    resource: "@AppFrontOfficeBundle/Resources/config/routing.yml"
    prefix:   /front-office

app_back_office:
    resource: "@AppBackOfficeBundle/Resources/config/routing.yml"
    prefix:   /back-office

AppBackOfficeBundle_type-demande:
        resource: "@AppBackOfficeBundle/Resources/config/routing/typedemande.yml"
        prefix:   /back-office/type-demande

AppBackOfficeBundle_type-reclamation:
    resource: "@AppBackOfficeBundle/Resources/config/routing/typereclamation.yml"
    prefix:   /back-office/type-reclamation

