app_front_office:
    resource: "@AppFrontOfficeBundle/Resources/config/routing.yml"
    prefix:   /front-office

app_back_office:
    resource: "@AppBackOfficeBundle/Resources/config/routing.yml"
    prefix:   /back-office

AppBackOfficeBundle_type-demande:
   resource: "@AppBackOfficeBundle/Resources/config/routing/typedemande.yml"
   prefix:   /back-office/configuration/type-demande

AppBackOfficeBundle_type-reclamation:
    resource: "@AppBackOfficeBundle/Resources/config/routing/typereclamation.yml"
    prefix:   /back-office/type-reclamation

AppBackOfficeBundle_admin:
    resource: "@AppBackOfficeBundle/Resources/config/routing/admin.yml"
    prefix:   /back-office/admin

AppBackOfficeBundle_notification-admin:
        resource: "@AppBackOfficeBundle/Resources/config/routing/notification.yml"
        prefix:   /back-office/notification-admin

AppFrontOfficeBundle_notification-etudiant:
        resource: "@AppFrontOfficeBundle/Resources/config/routing/notificationetudiant.yml"
        prefix:   /front-office/notification-etudiant